import type {
  Project,
  Session,
  FileNode,
  GitFile,
  Memory,
  Note,
  Skill,
  DiffHunk,
} from "./types"

export const projects: Project[] = [
  {
    id: "p1",
    name: "bosch-code",
    localPath: "~/dev/bosch-code",
    language: "Rust",
    framework: "Tauri",
    gitRemote: "github.com/bosch/bosch-code",
    gitBranch: "main",
    ciStatus: "passing",
    openedAt: "2026-06-27T10:30:00Z",
    createdAt: "2026-01-12T09:00:00Z",
    lastChatSummary: "重构记忆压缩器，使用版本链追踪压缩来源",
    pinned: true,
    kind: "local",
  },
  {
    id: "p2",
    name: "web-dashboard",
    localPath: "~/dev/web-dashboard",
    language: "TypeScript",
    framework: "Next.js",
    gitRemote: "github.com/acme/web-dashboard",
    gitBranch: "feat/auth",
    ciStatus: "running",
    openedAt: "2026-06-26T18:12:00Z",
    createdAt: "2026-03-02T11:00:00Z",
    lastChatSummary: "修复登录表单的会话过期问题并补充单元测试",
    pinned: true,
    kind: "local",
  },
  {
    id: "p3",
    name: "ml-pipeline",
    localPath: "~/dev/ml-pipeline",
    language: "Python",
    framework: "FastAPI",
    gitRemote: "github.com/lab/ml-pipeline",
    gitBranch: "main",
    ciStatus: "failing",
    openedAt: "2026-06-25T08:45:00Z",
    createdAt: "2026-02-20T14:00:00Z",
    lastChatSummary: "向量索引召回率下降，排查 embedding 维度不一致",
    kind: "local",
  },
  {
    id: "p4",
    name: "go-gateway",
    localPath: "/srv/go-gateway",
    language: "Go",
    framework: "Gin",
    gitRemote: "github.com/infra/go-gateway",
    gitBranch: "release/2.1",
    ciStatus: "passing",
    openedAt: "2026-06-22T16:30:00Z",
    createdAt: "2025-11-05T10:00:00Z",
    lastChatSummary: "为限流中间件增加白名单配置",
    kind: "ssh",
    sshHost: "prod-gateway-01",
  },
  {
    id: "p5",
    name: "design-system",
    localPath: "~/dev/design-system",
    language: "TypeScript",
    framework: "React",
    gitRemote: "github.com/acme/design-system",
    gitBranch: "main",
    ciStatus: "none",
    openedAt: "2026-06-18T09:10:00Z",
    createdAt: "2026-04-14T13:00:00Z",
    lastChatSummary: "统一按钮组件的尺寸 token",
    kind: "local",
  },
  {
    id: "p6",
    name: "edge-functions",
    localPath: "/srv/edge",
    language: "TypeScript",
    framework: "Hono",
    gitRemote: "github.com/infra/edge-functions",
    gitBranch: "main",
    ciStatus: "passing",
    openedAt: "2026-06-10T11:00:00Z",
    createdAt: "2026-05-01T08:00:00Z",
    lastChatSummary: "迁移到新的缓存 API",
    kind: "ssh",
    sshHost: "edge-runner-eu",
  },
]

const sampleDiff: DiffHunk = {
  filePath: "src/memory/compressor.rs",
  additions: 14,
  deletions: 6,
  language: "rust",
  status: "pending",
  lines: [
    { type: "meta", text: "@@ -42,9 +42,17 @@ impl MemoryCompressor {" },
    { type: "context", text: "    pub fn compress(&self, items: Vec<Memory>) -> Result<Memory> {", oldNo: 42, newNo: 42 },
    { type: "del", text: "        let summary = self.llm.summarize(&items)?;", oldNo: 43 },
    { type: "del", text: "        let version = 1;", oldNo: 44 },
    { type: "add", text: "        let summary = self.llm.summarize(&items)?;", newNo: 43 },
    { type: "add", text: "        // 追踪压缩来源以构建版本链", newNo: 44 },
    { type: "add", text: "        let sources: Vec<String> = items.iter().map(|m| m.id.clone()).collect();", newNo: 45 },
    { type: "add", text: "        let version = items.iter().map(|m| m.version).max().unwrap_or(0) + 1;", newNo: 46 },
    { type: "context", text: "        Ok(Memory {", oldNo: 45, newNo: 47 },
    { type: "add", text: "            compressed_from: Some(sources),", newNo: 48 },
    { type: "context", text: "            summary: Some(summary),", oldNo: 46, newNo: 49 },
    { type: "context", text: "            version,", oldNo: 47, newNo: 50 },
    { type: "context", text: "        })", oldNo: 48, newNo: 51 },
    { type: "context", text: "    }", oldNo: 49, newNo: 52 },
  ],
}

const testDiff: DiffHunk = {
  filePath: "src/memory/compressor_test.rs",
  additions: 22,
  deletions: 0,
  language: "rust",
  status: "pending",
  lines: [
    { type: "meta", text: "@@ -0,0 +1,22 @@" },
    { type: "add", text: "#[cfg(test)]", newNo: 1 },
    { type: "add", text: "mod tests {", newNo: 2 },
    { type: "add", text: "    use super::*;", newNo: 3 },
    { type: "add", text: "", newNo: 4 },
    { type: "add", text: "    #[test]", newNo: 5 },
    { type: "add", text: "    fn version_chain_increments() {", newNo: 6 },
    { type: "add", text: "        let c = MemoryCompressor::new();", newNo: 7 },
    { type: "add", text: "        let out = c.compress(vec![mem(1), mem(2)]).unwrap();", newNo: 8 },
    { type: "add", text: "        assert_eq!(out.version, 3);", newNo: 9 },
    { type: "add", text: "    }", newNo: 10 },
    { type: "add", text: "}", newNo: 11 },
  ],
}

export const sessions: Session[] = [
  {
    id: "s1",
    projectId: "p1",
    title: "重构记忆压缩器",
    mode: "edit",
    status: "active",
    pinned: true,
    updatedAt: "2026-06-27T10:30:00Z",
    tokenCount: 18420,
    messages: [
      {
        id: "m1",
        role: "user",
        content:
          "记忆压缩之后我无法追溯它是由哪些条目合并来的。帮我在 `MemoryCompressor::compress` 里加上版本链追踪，并补一个单元测试。",
        createdAt: "2026-06-27T10:20:00Z",
      },
      {
        id: "m2",
        role: "assistant",
        mode: "edit",
        content:
          "我先检索了相关上下文，理解了当前压缩逻辑。计划如下：\n\n1. 在 `compress` 中收集源记忆 ID 写入 `compressed_from`\n2. 版本号取源记忆最大版本 +1\n3. 新增 `compressor_test.rs` 验证版本链递增\n\n下面是生成的变更，请审阅后采纳。",
        createdAt: "2026-06-27T10:21:00Z",
        toolCalls: [
          { tool: "Retriever", args: "query: memory compression version", status: "success", result: "命中 4 条相关记忆" },
          { tool: "FileSearch", args: "compressor.rs", status: "success", result: "找到 1 个文件" },
          { tool: "CodeEditor", args: "apply patch ×2", status: "success", result: "2 个文件已生成补丁" },
        ],
        diffs: [sampleDiff, testDiff],
        fileRefs: ["src/memory/compressor.rs", "src/memory/compressor_test.rs"],
      },
    ],
  },
  {
    id: "s2",
    projectId: "p1",
    title: "FAISS 索引降级策略",
    mode: "plan",
    status: "active",
    updatedAt: "2026-06-26T15:00:00Z",
    tokenCount: 9200,
    messages: [
      {
        id: "m3",
        role: "user",
        content: "如果 FAISS 索引损坏，应该怎么降级？给我一个计划。",
        createdAt: "2026-06-26T14:50:00Z",
      },
      {
        id: "m4",
        role: "assistant",
        mode: "plan",
        content:
          "## 降级计划：FAISS 索引损坏\n\n1. **检测** — 启动时校验索引文件头与 entry_count\n2. **回退** — 切换到 SQLite 全文搜索（LIKE 查询）\n3. **后台重建** — 异步重新生成索引，完成后切回\n4. **用户提示** — 状态栏黄色图标 + “语义搜索暂时不可用”\n\n是否将此计划导出为 Plan 文档？",
        createdAt: "2026-06-26T14:52:00Z",
      },
    ],
  },
  {
    id: "s3",
    projectId: "p1",
    title: "解释 sandbox crate",
    mode: "ask",
    status: "archived",
    updatedAt: "2026-06-24T09:30:00Z",
    tokenCount: 4100,
    messages: [
      {
        id: "m5",
        role: "user",
        content: "sandbox crate 是怎么拦截网络访问的？",
        createdAt: "2026-06-24T09:25:00Z",
      },
      {
        id: "m6",
        role: "assistant",
        mode: "ask",
        content:
          "`sandbox` crate 在子进程启动前通过 OS 级机制限制网络：\n\n- **Linux**：seccomp-bpf 过滤 `connect`/`socket` 系统调用，仅放行白名单\n- **macOS**：seatbelt profile 拒绝 `network-outbound`\n- **Windows**：受限 Token 移除网络相关权限\n\n白名单由用户在设置中配置（如 `*.npmjs.org`）。",
        createdAt: "2026-06-24T09:26:00Z",
      },
    ],
  },
]

export const fileTree: FileNode[] = [
  {
    name: "src",
    path: "src",
    type: "dir",
    children: [
      {
        name: "memory",
        path: "src/memory",
        type: "dir",
        children: [
          { name: "mod.rs", path: "src/memory/mod.rs", type: "file" },
          { name: "compressor.rs", path: "src/memory/compressor.rs", type: "file", changed: "modified" },
          { name: "compressor_test.rs", path: "src/memory/compressor_test.rs", type: "file", changed: "added" },
          { name: "retriever.rs", path: "src/memory/retriever.rs", type: "file" },
        ],
      },
      {
        name: "git",
        path: "src/git",
        type: "dir",
        children: [
          { name: "manager.rs", path: "src/git/manager.rs", type: "file" },
          { name: "diff.rs", path: "src/git/diff.rs", type: "file" },
        ],
      },
      {
        name: "sandbox",
        path: "src/sandbox",
        type: "dir",
        children: [
          { name: "mod.rs", path: "src/sandbox/mod.rs", type: "file" },
          { name: "linux.rs", path: "src/sandbox/linux.rs", type: "file" },
        ],
      },
      { name: "main.rs", path: "src/main.rs", type: "file" },
      { name: "lib.rs", path: "src/lib.rs", type: "file" },
    ],
  },
  {
    name: "ui",
    path: "ui",
    type: "dir",
    children: [
      { name: "App.tsx", path: "ui/App.tsx", type: "file" },
      { name: "store.ts", path: "ui/store.ts", type: "file" },
    ],
  },
  { name: "Cargo.toml", path: "Cargo.toml", type: "file" },
  { name: "README.md", path: "README.md", type: "file" },
]

export const gitFiles: GitFile[] = [
  { path: "src/memory/compressor.rs", status: "modified", staged: true, additions: 14, deletions: 6 },
  { path: "src/memory/compressor_test.rs", status: "added", staged: true, additions: 22, deletions: 0 },
  { path: "src/memory/mod.rs", status: "modified", staged: false, additions: 1, deletions: 0 },
  { path: "docs/memory.md", status: "modified", staged: false, additions: 8, deletions: 2 },
  { path: "scratch.rs", status: "untracked", staged: false, additions: 0, deletions: 0 },
]

export const memories: Memory[] = [
  {
    id: "mem1",
    projectId: "p1",
    type: "fact",
    content: "项目使用 SQLite (rusqlite) + FAISS 作为记忆存储，向量维度为 768。",
    importance: 0.9,
    accessCount: 42,
    version: 1,
    encrypted: false,
    createdAt: "2026-02-01T10:00:00Z",
    lastAccessedAt: "2026-06-27T10:20:00Z",
  },
  {
    id: "mem2",
    projectId: "p1",
    type: "behavior",
    content: "用户偏好：每次代码修改后自动运行 `cargo test`，并要求补充单元测试。",
    importance: 0.85,
    accessCount: 31,
    version: 2,
    encrypted: false,
    createdAt: "2026-03-10T10:00:00Z",
    lastAccessedAt: "2026-06-27T09:00:00Z",
  },
  {
    id: "mem3",
    projectId: "p1",
    type: "interaction",
    content: "上周讨论过：push 操作必须需要用户确认，commit 可以自动执行。",
    summary: "push 需确认，commit 自动",
    importance: 0.7,
    accessCount: 12,
    version: 3,
    encrypted: false,
    createdAt: "2026-06-18T10:00:00Z",
    lastAccessedAt: "2026-06-25T14:00:00Z",
  },
  {
    id: "mem4",
    projectId: "p1",
    type: "fact",
    content: "API Key 存储在 OS 原生密钥链中，敏感记忆使用 AES-256-GCM 加密。",
    importance: 0.6,
    accessCount: 5,
    version: 1,
    encrypted: true,
    createdAt: "2026-04-02T10:00:00Z",
    lastAccessedAt: "2026-06-20T11:00:00Z",
  },
  {
    id: "mem5",
    projectId: "p1",
    type: "plan",
    content: "POC 阶段计划：验证 Tauri IPC 延迟、FAISS 三平台编译、Monaco 加载性能。",
    importance: 0.5,
    accessCount: 8,
    version: 1,
    encrypted: false,
    createdAt: "2026-01-20T10:00:00Z",
    lastAccessedAt: "2026-06-15T08:00:00Z",
  },
]

export const notes: Note[] = [
  {
    id: "n1",
    title: "压缩策略待办",
    body: "- 聚合相似条目时使用 cosine > 0.92 阈值\n- 版本链最多保留 5 层，再老的折叠为摘要\n- 加密条目压缩前需先解密",
    updatedAt: "2026-06-27T08:00:00Z",
  },
  {
    id: "n2",
    title: "性能基线",
    body: "FAISS 1 万条检索目标 < 50ms；Diff 渲染 5000 行 < 500ms。",
    updatedAt: "2026-06-24T08:00:00Z",
  },
]

export const skills: Skill[] = [
  {
    id: "sk1",
    name: "run-tests",
    description: "在沙箱内运行项目测试套件并解析结果",
    version: "1.2.0",
    source: "builtin",
    permissions: ["shell"],
    enabled: true,
  },
  {
    id: "sk2",
    name: "format",
    description: "使用项目配置的格式化工具格式化变更文件",
    version: "1.0.3",
    source: "builtin",
    permissions: ["write-project"],
    enabled: true,
  },
  {
    id: "sk3",
    name: "lint",
    description: "运行静态检查并将问题反馈给 Agent",
    version: "0.9.1",
    source: "builtin",
    permissions: ["shell", "read-only"],
    enabled: true,
  },
  {
    id: "sk4",
    name: "github-pr",
    description: "根据当前变更生成 PR 草稿",
    version: "2.1.0",
    source: "registry",
    permissions: ["git", "network"],
    enabled: false,
  },
]

export const slashCommands = [
  { cmd: "/run-tests", desc: "运行测试套件" },
  { cmd: "/format", desc: "格式化变更文件" },
  { cmd: "/lint", desc: "运行静态检查" },
  { cmd: "/plan", desc: "切换到计划模式并生成计划" },
  { cmd: "/commit", desc: "提交当前已暂存的变更" },
  { cmd: "/explain", desc: "解释选中的文件或符号" },
]
